# 数据区间
# ===== JQData 账号类型 =====
account_type: trial      # trial = 试用（15→3 个月） | formal = 正式（不限制）

# ===== 自动日期区间 =====
# 试用账号：前 15 个月 ~ 前 3 个月
# 正式账号：2019-01-01 ~ 2024-06-30（可任意改）
date_cfg:
  trial:
    start: AUTO   # 脚本自动计算
    end:   AUTO
  formal:
    start: 2019-01-01
    end:   2024-06-30

# ===== 其余配置保持原样 =====
jq_user: 'YOUR_JQ_PHONE'
jq_pass: 'YOUR_JQ_PASSWORD#'

univ:
  - '000300.XSHG'   # 沪深300
  - '000905.XSHG'   # 中证500
  - '399006.XSHE'   # 创业板指

# 路径
raw_dir: ./data/raw
feature_dir: ./data/features
result_dir: ./results

# 特征参数
vpin_buckets: 50
rv_minutes: 240
tr_window: 30          # 收盘前 30 min 成交量
zscore_window: 60

# 训练
roll_train_days: 360
roll_valid_days: 60
roll_test_days: 60
optuna_trials: 64
lgb_params:
  objective: binary
  metric: auc
  verbosity: -1
  boost_from_average: false
  focal_alpha: 0.75
  focal_gamma: 2.0

# 交易假设
cost: 0.003   # 单边 0.3%
